apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    tier: rapidfire-app
  name: app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30009
  selector:
    tier: rapidfire-app
  type: LoadBalancer
status:
  loadBalancer: {}
