apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    tier: postgres-db
  name: db-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    tier: postgres-db
  type: ClusterIP
status:
  loadBalancer: {}
